services:
  - type: web
    name: skoob-sync-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y wget gnupg ca-certificates && \
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
      apt-get update && \
      apt-get install -y google-chrome-stable && \
      pip install -r requirements.txt
    startCommand: "gunicorn api:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4